# Write a workflow to go into NebulaRoot and run "npm start -- generate distro" and then after completed, upload the distribution.json file in NebulaRoot to Cloudflare Pages.
name: Create Distro
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Distro
        run: npm start -- generate distro