name: Create Distro
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Replace Java Path
        working-directory: "Nebula/NebulaRepo"
        run: sed -i 's/JAVA_EXECUTABLE=.*/JAVA_EXECUTABLE=\/usr\/lib\/jvm\/temurin-21-jdk-amd64\/bin\/java/g' .env

      - name: Install dependencies
        working-directory: "Nebula/NebulaRepo"
        run: npm install

      - name: Init root
        working-directory: "Nebula/NebulaRepo"
        run: npm run start -- init root

      - name: Generate Distro
        working-directory: "Nebula/NebulaRepo"
        run: npm start -- generate distro

      - uses: vimtor/action-zip@v1.2
        with:
          files: "./Nebula/NebulaRoot/"
          dest: result.zip

      - name: Upload zip to Whalebone
        run: |
          UPLOAD_URL=$(curl --upload-file ./result.zip https://transfer.whalebone.io/)
          echo "$UPLOAD_URL" > upload_url.txt
          cat upload_url.txt
        shell: bash

      - name: Save upload URL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload_url
          path: upload_url.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download upload URL artifact
        uses: actions/download-artifact@v4
        with:
          name: upload_url

      - name: Read upload URL
        id: get_url
        run: echo "UPLOAD_URL=$(cat upload_url.txt)" >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: epochdistupload
          password: ${{ secrets.SSH_PWD }}
          port: ${{ secrets.PORT }}
          script: |
            cd webroot && rm -r * || true
            wget $UPLOAD_URL -O result.zip
            unzip result.zip
