# Write a workflow to go into NebulaRoot and run "npm start -- generate distro" and then after completed, upload the distribution.json file in NebulaRoot to Cloudflare Pages.
name: Create Distro
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      # Write a step to go into Nebula/NebulaRepo and replace the Java path in .env with /usr/lib/jvm/temurin-21-jdk-amd64/bin/java relying on just the start of the line. JAVA_EXECUTABLE=
      - name: Replace Java Path
        working-directory: "Nebula/NebulaRepo"
        run: sed -i 's/JAVA_EXECUTABLE=.*/JAVA_EXECUTABLE=\/usr\/lib\/jvm\/temurin-21-jdk-amd64\/bin\/java/g' .env

      - name: Install dependencies
        working-directory: "Nebula/NebulaRepo"
        run: npm install

      - name: Init root
        working-directory: "Nebula/NebulaRepo"
        run: npm run start -- init root

      - name: Generate Distro
        working-directory: "Nebula/NebulaRepo"
        run: npm start -- generate distro

      - uses: vimtor/action-zip@v1.2
        with:
          files: "./Nebula/NebulaRoot/"
          dest: result.zip

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        allow_failure: true
        with:
          host: ${{ secrets.HOST }}
          username: epochdistupload
          password: ${{ secrets.SSH_PWD }}
          port: ${{ secrets.PORT }}
          script: cd webroot && rm -r .

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: panel.epochcraft.space
          username: "artificialai.cc7fc867"
          password: ${{ secrets.SFTP_PWD }}
          port: 2022
          uploads: |
            ./ => ./webroot
          ignore: |
            !result.zip

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: epochdistupload
          password: ${{ secrets.SSH_PWD }}
          port: ${{ secrets.PORT }}
          script: cd webroot && unzip result.zip