# Write a workflow to go into NebulaRoot and run "npm start -- generate distro" and then after completed, upload the distribution.json file in NebulaRoot to Cloudflare Pages.
name: Create Distro
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      # Write a step to go into Nebula/NebulaRepo and replace the Java path in .env with /usr/lib/jvm/temurin-21-jdk-amd64/bin/java relying on just the start of the line. JAVA_EXECUTABLE=
      - name: Replace Java Path
        working-directory: "Nebula/NebulaRepo"
        run: sed -i 's/JAVA_EXECUTABLE=.*/JAVA_EXECUTABLE=\/usr\/lib\/jvm\/temurin-21-jdk-amd64\/bin\/java/g' .env

      - name: Install dependencies
        working-directory: "Nebula/NebulaRepo"
        run: npm install

      - name: Init root
        working-directory: "Nebula/NebulaRepo"
        run: npm run start -- init root

      - name: Generate Distro
        working-directory: "Nebula/NebulaRepo"
        run: npm start -- generate distro

      - name: 📂 SFTP uploader # Upload to SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: panel.epochcraft.space # Recommended to put the credentials in github secrets.
          username: "artificialai.cc7fc867"
          password: ${{ secrets.SFTP_PWD }}
          compress: true # Compression
          forceUpload: true # Optional, Force uploading all files, Default to false(upload only newer files).
          localDir: "./Nebula/NebulaRoot" # Required, Absolute or relative to cwd.
          remoteDir: "/webroot" # Required, Absolute path only.